# fly.toml app configuration file generated for alekarhis-phonebook-backend on 2024-01-20T02:39:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alekarhis-phonebook-backend"
primary_region = "waw"

[build]

[env]
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
